### PR TITLE
Add zuul-ci

### PR DESCRIPTION
**Pull request by matofeder**

### CODE REVIEW

**Comment by matofeder** [comment]
recheck

**Comment by matofeder** [comment]
recheck

**Comment by matofeder** [comment]
recheck

**Comment by matofeder** [comment]
recheck

**Comment by matofeder** [comment]
recheck

**Comment by matofeder** [comment]
recheck

**Comment by matofeder** [comment]
recheck

**Comment by matofeder** [comment]
recheck

**Comment by matofeder** [comment]
recheck

**Comment by matofeder** [comment]
recheck

**Comment by matofeder** [comment]
recheck

**Comment by matofeder** [comment]
recheck

**Comment by matofeder** [comment]
recheck

**Comment by matofeder** [comment]
recheck

**Comment by matofeder** [comment]
recheck

**Review by matofeder — COMMENTED** [review]
regate

**Review by matofeder — COMMENTED** [review]
/test_conformance

**Comment by matofeder** [comment]
test-conformance

**Review by matofeder — COMMENTED** [review]
test-conformance

**Review by ghost — COMMENTED** [review]
test-conformance

**Comment by matofeder** [comment]
recheck

**Pull request closed without merging**
